import { Category } from "@/types/models";

export const categories: Category[] = [
  {
    id: "web-design",
    name: "Web Design",
    description: "Interactive websites, landing pages, and web applications designed by AI models.",
    color: "#3B82F6"
  },
  {
    id: "code-generation",
    name: "Code",
    description: "Programming solutions and implementations across various languages and frameworks.",
    color: "#10B981"
  },
  {
    id: "image-generation",
    name: "Images",
    description: "Visual content including digital art, realistic renders, and creative graphics.",
    color: "#8B5CF6"
  },
  {
    id: "text-analysis",
    name: "Text Analysis",
    description: "Comprehensive text processing, summarization, and analytical capabilities.",
    color: "#F97316"
  },
  {
    id: "reasoning",
    name: "Reasoning",
    description: "Complex problem-solving and logical reasoning capabilities demonstrated by AI.",
    color: "#EC4899"
  },
  {
    id: "creative-writing",
    name: "Creative",
    description: "Stories, poems, scripts and other creative writing generated by AI models.",
    color: "#14B8A6"
  }
]; 